FROM openjdk:11.0.6-jre

ADD target/DeviceSimulator-1.0-jar-with-dependencies.jar DeviceSimulator-1.0-jar-with-dependencies.jar
ENTRYPOINT ["java", "-jar", "DeviceSimulator-1.0-jar-with-dependencies.jar"]
EXPOSE 8080
