/**
 * @fileoverview gRPC-Web generated client stub for 
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.4.2
// 	protoc              v4.22.0
// source: chat.proto


/* eslint-disable */
// @ts-nocheck



const grpc = {};
grpc.web = require('grpc-web');

const proto = require('./chat_pb.js');

/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.ChatServiceClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.ChatServicePromiseClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.Message,
 *   !proto.Empty>}
 */
const methodDescriptor_ChatService_sendMessage = new grpc.web.MethodDescriptor(
  '/ChatService/sendMessage',
  grpc.web.MethodType.UNARY,
  proto.Message,
  proto.Empty,
  /**
   * @param {!proto.Message} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.Empty.deserializeBinary
);


/**
 * @param {!proto.Message} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.Empty)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.Empty>|undefined}
 *     The XHR Node Readable Stream
 */
proto.ChatServiceClient.prototype.sendMessage =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/ChatService/sendMessage',
      request,
      metadata || {},
      methodDescriptor_ChatService_sendMessage,
      callback);
};


/**
 * @param {!proto.Message} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.Empty>}
 *     Promise that resolves to the response
 */
proto.ChatServicePromiseClient.prototype.sendMessage =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/ChatService/sendMessage',
      request,
      metadata || {},
      methodDescriptor_ChatService_sendMessage);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.User,
 *   !proto.Message>}
 */
const methodDescriptor_ChatService_receiveMessage = new grpc.web.MethodDescriptor(
  '/ChatService/receiveMessage',
  grpc.web.MethodType.SERVER_STREAMING,
  proto.User,
  proto.Message,
  /**
   * @param {!proto.User} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.Message.deserializeBinary
);


/**
 * @param {!proto.User} request The request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!grpc.web.ClientReadableStream<!proto.Message>}
 *     The XHR Node Readable Stream
 */
proto.ChatServiceClient.prototype.receiveMessage =
    function(request, metadata) {
  return this.client_.serverStreaming(this.hostname_ +
      '/ChatService/receiveMessage',
      request,
      metadata || {},
      methodDescriptor_ChatService_receiveMessage);
};


/**
 * @param {!proto.User} request The request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!grpc.web.ClientReadableStream<!proto.Message>}
 *     The XHR Node Readable Stream
 */
proto.ChatServicePromiseClient.prototype.receiveMessage =
    function(request, metadata) {
  return this.client_.serverStreaming(this.hostname_ +
      '/ChatService/receiveMessage',
      request,
      metadata || {},
      methodDescriptor_ChatService_receiveMessage);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.User,
 *   !proto.TypingUser>}
 */
const methodDescriptor_ChatService_subscribeForTypingUser = new grpc.web.MethodDescriptor(
  '/ChatService/subscribeForTypingUser',
  grpc.web.MethodType.SERVER_STREAMING,
  proto.User,
  proto.TypingUser,
  /**
   * @param {!proto.User} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.TypingUser.deserializeBinary
);


/**
 * @param {!proto.User} request The request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!grpc.web.ClientReadableStream<!proto.TypingUser>}
 *     The XHR Node Readable Stream
 */
proto.ChatServiceClient.prototype.subscribeForTypingUser =
    function(request, metadata) {
  return this.client_.serverStreaming(this.hostname_ +
      '/ChatService/subscribeForTypingUser',
      request,
      metadata || {},
      methodDescriptor_ChatService_subscribeForTypingUser);
};


/**
 * @param {!proto.User} request The request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!grpc.web.ClientReadableStream<!proto.TypingUser>}
 *     The XHR Node Readable Stream
 */
proto.ChatServicePromiseClient.prototype.subscribeForTypingUser =
    function(request, metadata) {
  return this.client_.serverStreaming(this.hostname_ +
      '/ChatService/subscribeForTypingUser',
      request,
      metadata || {},
      methodDescriptor_ChatService_subscribeForTypingUser);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.TypingNotification,
 *   !proto.Empty>}
 */
const methodDescriptor_ChatService_notifyReceiverIsTyping = new grpc.web.MethodDescriptor(
  '/ChatService/notifyReceiverIsTyping',
  grpc.web.MethodType.UNARY,
  proto.TypingNotification,
  proto.Empty,
  /**
   * @param {!proto.TypingNotification} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.Empty.deserializeBinary
);


/**
 * @param {!proto.TypingNotification} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.Empty)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.Empty>|undefined}
 *     The XHR Node Readable Stream
 */
proto.ChatServiceClient.prototype.notifyReceiverIsTyping =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/ChatService/notifyReceiverIsTyping',
      request,
      metadata || {},
      methodDescriptor_ChatService_notifyReceiverIsTyping,
      callback);
};


/**
 * @param {!proto.TypingNotification} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.Empty>}
 *     Promise that resolves to the response
 */
proto.ChatServicePromiseClient.prototype.notifyReceiverIsTyping =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/ChatService/notifyReceiverIsTyping',
      request,
      metadata || {},
      methodDescriptor_ChatService_notifyReceiverIsTyping);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.User,
 *   !proto.User>}
 */
const methodDescriptor_ChatService_subscribeToMessageHasBeenRead = new grpc.web.MethodDescriptor(
  '/ChatService/subscribeToMessageHasBeenRead',
  grpc.web.MethodType.SERVER_STREAMING,
  proto.User,
  proto.User,
  /**
   * @param {!proto.User} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.User.deserializeBinary
);


/**
 * @param {!proto.User} request The request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!grpc.web.ClientReadableStream<!proto.User>}
 *     The XHR Node Readable Stream
 */
proto.ChatServiceClient.prototype.subscribeToMessageHasBeenRead =
    function(request, metadata) {
  return this.client_.serverStreaming(this.hostname_ +
      '/ChatService/subscribeToMessageHasBeenRead',
      request,
      metadata || {},
      methodDescriptor_ChatService_subscribeToMessageHasBeenRead);
};


/**
 * @param {!proto.User} request The request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!grpc.web.ClientReadableStream<!proto.User>}
 *     The XHR Node Readable Stream
 */
proto.ChatServicePromiseClient.prototype.subscribeToMessageHasBeenRead =
    function(request, metadata) {
  return this.client_.serverStreaming(this.hostname_ +
      '/ChatService/subscribeToMessageHasBeenRead',
      request,
      metadata || {},
      methodDescriptor_ChatService_subscribeToMessageHasBeenRead);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.ReadNotification,
 *   !proto.Empty>}
 */
const methodDescriptor_ChatService_notifyReceiverHasReadMessages = new grpc.web.MethodDescriptor(
  '/ChatService/notifyReceiverHasReadMessages',
  grpc.web.MethodType.UNARY,
  proto.ReadNotification,
  proto.Empty,
  /**
   * @param {!proto.ReadNotification} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.Empty.deserializeBinary
);


/**
 * @param {!proto.ReadNotification} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.Empty)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.Empty>|undefined}
 *     The XHR Node Readable Stream
 */
proto.ChatServiceClient.prototype.notifyReceiverHasReadMessages =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/ChatService/notifyReceiverHasReadMessages',
      request,
      metadata || {},
      methodDescriptor_ChatService_notifyReceiverHasReadMessages,
      callback);
};


/**
 * @param {!proto.ReadNotification} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.Empty>}
 *     Promise that resolves to the response
 */
proto.ChatServicePromiseClient.prototype.notifyReceiverHasReadMessages =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/ChatService/notifyReceiverHasReadMessages',
      request,
      metadata || {},
      methodDescriptor_ChatService_notifyReceiverHasReadMessages);
};


module.exports = proto;

